homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: Europe/Amsterdam
  currency: EUR
  unit_system: metric
  packages: !include_dir_named includes

lovelace:
  mode: yaml
  
frontend:
  themes: !include_dir_merge_named themes

mobile_app: