title: Home
views:
  - path: default_view
    title: Home
    theme: Google Dark Theme
    icon: mdi:lamps
    badges: []
    cards:
      - type: entities
        title: Kitchen Lights
        entities:
          - entity: light.kitchen_spot_left
            name: Spot Left
          - entity: light.kitchen_spot_right
            name: Spot Right
        header:
          type: buttons
          entities: []
        footer:
          type: buttons
          entities: []
        theme: Google Dark Theme
        state_color: true
      - type: entities
        title: Lounge Lights
        entities:
          - entity: light.lounge_bulb_m_t
            name: TV Top
          - entity: light.lounge_bulb_m_d
            name: TV Down
          - entity: light.lounge_bulb_l_t
            name: Couch Top
          - entity: light.lounge_bulb_l_m
            name: Couch Center
          - entity: light.lounge_bulb_l_d
            name: Couch Down
          - entity: light.lounge_bulb_s
            name: Dining Table
        header:
          type: buttons
          entities: []
        footer:
          type: buttons
          entities: []
        theme: Google Dark Theme
        state_color: true
  - title: Phone
    path: phone
    icon: mdi:cellphone
    theme: Google Dark Theme
    badges: []
    cards: 
      - type: entity
        entity: binary_sensor.s20_is_charging
        name: S20 Charging
      - type: entity
        entity: sensor.s20_battery_health
        name: S20 Battery Health
      - type: entity
        entity: sensor.s20_battery_state
        name: S20 Battery State
      - type: entity
        entity: sensor.s20_battery_temperature
        name: S20 Battery Temperature
      - type: entity
        entity: sensor.s20_geocoded_location
        name: S20 Geocoded Location
      - type: entity
        entity: sensor.s20_next_alarm
        name: S20 Next Alarm
      - type: entity
        entity: sensor.s20_light_sensor
        name: S20 Light Sensor
      - type: entity
        entity: sensor.s20_do_not_disturb_sensor
        name: S20 Do Not Disturb