homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: Europe/Amsterdam
  currency: EUR
  unit_system: metric
  packages: !include_dir_named includes

lovelace:
  mode: yaml
  resources:
  - url: /local/home-assistant-sun-card.js
    type: module

frontend:
mobile_app:
energy:
sun:
   
influxdb:
  api_version: 2
  host: !secret influxdb_ip
  port: !secret influxdb_port
  bucket: !secret influxdb_bucket
  token: !secret influxdb_token
  organization: !secret influxdb_organization
  ssl: false