title: Home
views:
  - title: Home
    path: default_view
    icon: mdi:lamps
    badges: []
    cards:
      - type: 'custom:sun-card'
      - type: media-control
        entity: media_player.master_bedroom_tv
        name: Chromecast
      - type: entities
        title: Kitchen Lights
        entities:
          - entity: light.wiz_spot_l
            name: Spot Left
          - entity: light.wiz_spot_r
            name: Spot Right
        state_color: true
      - type: entities
        title: Lounge Lights
        entities:
          - entity: light.wiz_twr_22
            name: TV Top
          - entity: light.wiz_twr_21
            name: TV Down
          - entity: light.wiz_twr_33
            name: Couch Top
          - entity: light.wiz_twr_32
            name: Couch Center
          - entity: light.wiz_twr_31
            name: Couch Down
          - entity: light.wiz_twr_11
            name: Dining Table
        state_color: true
      - type: entities
        entities:
          - entity: binary_sensor.btn_blue
            name: "Blue: toggle light"
          - entity: binary_sensor.btn_red
            name: "Red: send notification"
        title: Custom Sensors

  - title: Phone Sensors
    path: phone
    icon: mdi:cellphone
    badges: []
    cards: 
      - type: entity
        entity: binary_sensor.s20_is_charging
        name: S20 Charging
      - type: entity
        entity: sensor.s20_battery_health
        name: S20 Battery Health
      - type: entity
        entity: sensor.s20_battery_state
        name: S20 Battery State
      - type: entity
        entity: sensor.s20_battery_temperature
        name: S20 Battery Temperature
      - type: entity
        entity: sensor.s20_geocoded_location
        name: S20 Geocoded Location
      - type: entity
        entity: sensor.s20_next_alarm
        name: S20 Next Alarm
      - type: entity
        entity: sensor.s20_do_not_disturb_sensor
        name: S20 Do Not Disturb
      - type: entity
        entity: sensor.s20_battery_level
        
  - title: Power Consumption (temp)
    path: house
    icon: mdi:home
    badges: []
    cards:
      - type: entity
        entity: sensor.power_tariff
        name: Tarief       
      - type: history-graph
        title: 'Power Consumption'
        entities: 
          - entity: sensor.energy_consumption_tarif_1
          - entity: sensor.energy_consumption_tarif_2
          - entity: sensor.energy_production_tarif_1
          - entity: sensor.energy_production_tarif_2
      - type: history-graph
        title: 'Power Consumption 2.0'
        entities: 
          - sensor.power_consumption
          - sensor.power_production
      - type: statistics-graph
        title: 'Power Consumption 3.0'
        entities:
          - sensor.power_consumption
          - sensor.power_production
          
        
      
